"""Table and column names - single source of truth."""

SOURCES = "sources"
NEWS_ITEMS = "news_items"
STORIES = "stories"
STORY_SOURCES = "story_sources"
CLAIMS = "claims"
EVIDENCE = "evidence"
PUBLICATIONS = "publications"

COL_ID = "id"
COL_STORY_ID = "story_id"
COL_NEWS_ITEM_ID = "news_item_id"
COL_SOURCE_ID = "source_id"
COL_CLAIM_ID = "claim_id"
COL_TITLE = "title"
COL_URL = "url"
COL_CANONICAL_URL = "canonical_url"
COL_STATUS = "status"
COL_FIRST_SEEN_AT = "first_seen_at"
COL_LAST_SEEN_AT = "last_seen_at"
COL_DISCOVERED_AT = "discovered_at"
COL_PUBLISHED_AT = "published_at"
COL_PLATFORM = "platform"
COL_EXTERNAL_POST_ID = "external_post_id"
COL_CONTENT = "content"
COL_METADATA = "metadata"
COL_RELATIONSHIP = "relationship"
COL_SOURCE_TYPE = "source_type"
COL_SOURCE_NAME = "source_name"
COL_SOURCE_DOMAIN = "source_domain"

STORY_STATUS_CANDIDATE = "candidate"
STORY_STATUS_RESEARCHING = "researching"
STORY_STATUS_VERIFIED = "verified"
STORY_STATUS_EDITORIAL = "editorially_approved"
STORY_STATUS_DRAFTED = "drafted"
STORY_STATUS_PUBLISHED = "published"
STORY_STATUS_BLOCKED = "blocked"
STORY_STATUS_REJECTED = "rejected"

CLAIM_STATUS_UNVERIFIED = "unverified"
CLAIM_STATUS_SUPPORTED = "supported"
CLAIM_STATUS_SUPPORTED_AS_ATTRIBUTED = "supported_as_attributed"
CLAIM_STATUS_PARTIALLY_SUPPORTED = "partially_supported"
CLAIM_STATUS_CONTRADICTED = "contradicted"
CLAIM_STATUS_UNCERTAIN = "uncertain"

PUBLICATION_STATUS_DRAFT = "draft"
PUBLICATION_STATUS_APPROVED = "approved"
PUBLICATION_STATUS_PUBLISHING = "publishing"
PUBLICATION_STATUS_PUBLISHED = "published"
PUBLICATION_STATUS_DRY_RUN = "dry_run"
PUBLICATION_STATUS_FAILED = "failed"
PUBLICATION_STATUS_BLOCKED = "blocked"

PLATFORM_THREADS = "threads"
RELATIONSHIP_REPORTED_BY = "reported_by"
